version: '3'
services:
  client:
    image: rontor-server:latest
    environment:
      PORT: 3000
    ports:
      - '3003:3000'
    restart: always
  server:
    image: rontor-server:latest
    environment:
      DB_HOST: '192.168.0.3'
      DB_PORT: '3306'
      DB_NAME: 'rontor'
      DB_USER: 'root'
      DB_PASSWORD: 'Cbot2016!'
    ports:
      - '7777:7777'
    restart: always
